# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tik_tok_clone_native' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'GoogleSignInSwiftSupport'
pod 'GoogleSignIn'
pod 'SnackBar.swift'
pod 'Kingfisher'
pod 'ProgressHUD'
pod 'RealmSwift'
pod 'PDFGenerator'
pod 'Cosmos'



  # Pods for tik_tok_clone_native

end


post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
